version: '3'
services:
    mariadb:
        image: 'mariadb:10'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'car_store'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './mariadb:/var/lib/mysql'